print("sanni".capitalize())
print("MaRiO".casefold())
print("center".center(40, "-"))
print("abcabcabc".count(("ab")))
print("Elon Musk".encode(encoding="UTF-8", errors="strict"))
print("apple".endswith("a"))
print("tabs\ttabs\t".expandtabs(40))
print("Find name".find("name"))
print("The name is {subject} and he's a {action} developer".format(subject="sanni", action="Backend"))
print("{x}, {y}".format_map({"x": 30, "y": 50}))
print("Get the Index Positon of (1)".index("1"))
print("+".isalnum())
print("12".isalpha())