print("sanni".capitalize())
print("MaRiO".casefold())
print("center".center(40, "-"))
print("abcabcabc".count(("ab")))
print("Elon Musk".encode(encoding="UTF-8", errors="strict"))
print("apple".endswith("a"))
print("tabs\ttabs\t".expandtabs(40))
print("Find name".find("name"))
print("The name is {subject} and he's a {action} developer".format(subject="sanni", action="Backend"))
print("{x}, {y}".format_map({"x": 30, "y": 50}))
print("Get the Index Positon of (1)".index("1"))
print("+".isalnum())
print("12".isalpha())
print("2232".isascii())
print("12209302".isdecimal())
print("11".isdigit())
print("123".isnumeric())
print("iden-tifier".isidentifier())
print("isloweR".islower())
print("isprin-table".isprintable())
print(" ".isspace())
print("is title".istitle())
print("isupper".isupper())
print(" ".join((["bola", "anu"])))
print("test".ljust(20), "-")
print("LOWER".lower())
print("l strip".lstrip("l"))
print("Anni is the name".maketrans("A", "S"))
print("a-b-c".partition("-"))
print("Remove the Remove".removeprefix("Remove"))
print("Remove U".removesuffix("U"))
print("Replace M with W".replace("M", "W", 0))
print("A and  A".rfind("A"))
print("B and           B".rindex("B"))
print("rjust".rjust(20, "_"))
print("text=text=text".rpartition("="))
print("r-s-p-l-it".rsplit("-"))
print("Mario Mario".rstrip("Mario"))
print("I Love\nCoding".splitlines())
print("stat".startswith("d"))
print("Luigig".strip("L"))
print("lu".swapcase())
print("title".istitle())
print("make capital".upper())
print("text".zfill(30))