print("sanni".capitalize())
print("MaRiO".casefold())
print("center".center(40, "-"))
print("abcabcabc".count(("ab")))
print("Elon Musk".encode(encoding="UTF-8", errors="strict"))
print("apple".endswith("a"))
print()